CREATE DATABASE QueryStudy;
USE QueryStudy;

-- 1. Tabela BANCO
CREATE TABLE BANCO (
    idBanco INT AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(100) NOT NULL,
    cor VARCHAR(50)
);

-- 2. Tabela COMANDO
CREATE TABLE COMANDO (
    idComando INT AUTO_INCREMENT PRIMARY KEY,
    idBanco INT NOT NULL,
    comando TEXT, 
    FOREIGN KEY (idBanco) REFERENCES BANCO(idBanco)
        ON DELETE CASCADE 
        ON UPDATE CASCADE
);

-- 3. Tabela QUERY 
CREATE TABLE QUERY (
    idQuery INT AUTO_INCREMENT PRIMARY KEY,
    descricao VARCHAR(255)
);

-- 4. Tabela QUERY_COMANDO
CREATE TABLE QUERY_COMANDO (
    idQuery INT NOT NULL,
    idComando INT NOT NULL,
    ordem TINYINT, 
    PRIMARY KEY (idQuery, idComando), 
    FOREIGN KEY (idQuery) REFERENCES QUERY(idQuery)
        ON DELETE CASCADE 
        ON UPDATE CASCADE,
    FOREIGN KEY (idComando) REFERENCES COMANDO(idComando)
        ON DELETE CASCADE 
        ON UPDATE CASCADE
);

-- 5. Tabela HISTORICO 
CREATE TABLE HISTORICO (
    idHistorico INT AUTO_INCREMENT PRIMARY KEY,
    idQuery INT NOT NULL,
    data DATE, 
    FOREIGN KEY (idQuery) REFERENCES QUERY(idQuery)
        ON DELETE CASCADE 
        ON UPDATE CASCADE
);